### ISSUE TITLE
Add unit tests covering Lead operator field changes

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-dynamics#19]
## What / Why
Although not necessary to exercise every operator in tests (this should be covered by run-crank/typescript-cog-utilities#5), we should at least cover a few new branches of code and ensure the field is set correctly

## Scope / UAT Target
- [ ] Add operator field assertion in "expected step fields" test for Dynamics Lead Check Step
  - [ ] Field is set with expected key
  - [ ] Field is set to optional
- [ ] Add error outcome assertion when `util.compare` throws UnknownOperatorError for Dynamics Lead Check Step
- [ ] Add error outcome assertion when `util.compare` throws InvalidOperandError for Dynamics Lead Check Step

**Comment by amcpanaligan** [comment]
Also completed by @saludangelito before:

https://github.com/run-crank/cog-dynamics/blob/master/test/steps/lead-field-equals.ts#L409
https://github.com/run-crank/cog-dynamics/blob/master/test/steps/lead-field-equals.ts#L376
